version: "3.4"
volumes:
  data-volume:
services:
  db:
    restart: always
    container_name: sqlserver-drury-rmis
    image: "microsoft/mssql-server-linux"
    ports:
      - "1436:1433"
    volumes:
      - "data-volume:/var/opt/mssql/data"
    environment:
      SA_PASSWORD: "localdevpassE##E3343"
      ACCEPT_EULA: "Y"
  api:
    build: .
    ports:
        - "8001:80"
    depends_on:
        - db
    environment:
      WAIT_HOSTS: db:1433
